// ============================================================
//  PHI — Product Data Layer  |  products.js
//  Edit this file to add, update, or remove products.
//  All rendering is handled automatically by script.js.
//
//  NEW FIELDS (v4):
//    - stock: number of units remaining (shows "Only X left" when low)
//    - images: array of image URLs for the product gallery
//    - isNew: boolean — appears in the "New Arrivals" section
//    - details: { material, care, fit, weight } — shown in product modal
// ============================================================

const PRODUCTS = [
  {
    id: 'nm-001',
    name: { en: 'Classic T-Shirt', ar: 'تي شيرت كلاسيك' },
    desc: {
      en: 'Lightweight, breathable fabric — perfect for training or everyday wear.',
      ar: 'قماش خفيف ومريح — مثالي للتمرين أو الاستخدام اليومي.',
    },
    price: 50,
    originalPrice: null,
    category: 'tops',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Red',   nameAr: 'أحمر', hex: '#DC2626' },
      { name: 'Blue',  nameAr: 'أزرق', hex: '#2563EB' },
      { name: 'Black', nameAr: 'أسود', hex: '#1E293B' },
    ],
    image: 'images/IMG_٢٠٢٢١٢٢٢_١٥٢٥٤٨.jpg',
    images: [
      'images/IMG_٢٠٢٢١٢٢٢_١٥٢٥٤٨.jpg',
      'images/IMG_٢٠٢٢١٢٢٦_١٩٢٦١٣.jpg',
      'images/IMG_٢٠٢٣٠٤١٠_١٦٣٤٢٨(1).jpg',
    ],
    badge: 'bestseller',
    rating: 4.9,
    reviewCount: 48,
    inStock: true,
    stock: 12,
    featured: true,
    isNew: false,
    details: {
      material: { en: '100% Cotton — 180 GSM', ar: '100% قطن — 180 جرام/م²' },
      care:     { en: 'Machine wash cold, tumble dry low', ar: 'يُغسل في الغسالة بالماء البارد' },
      fit:      { en: 'Regular fit', ar: 'قصة عادية' },
      weight:   { en: '~200g', ar: '~200 جرام' },
    },
  },
  {
    id: 'nm-002',
    name: { en: 'Fleece Hoodie', ar: 'هودي فليس' },
    desc: {
      en: 'Cozy fleece interior — stay warm in style on and off the court.',
      ar: 'بطانة فليس دافئة — ابق دافئاً بستايل داخل وخارج الملعب.',
    },
    price: 120,
    originalPrice: 150,
    category: 'tops',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Red',   nameAr: 'أحمر', hex: '#DC2626' },
      { name: 'Blue',  nameAr: 'أزرق', hex: '#2563EB' },
      { name: 'Black', nameAr: 'أسود', hex: '#1E293B' },
    ],
    image: 'images/IMG_٢٠٢٢١٢٢٦_١٩٢٦١٣.jpg',
    images: [
      'images/IMG_٢٠٢٢١٢٢٦_١٩٢٦١٣.jpg',
      'images/IMG_٢٠٢٢١٢٢٢_١٥٢٥٤٨.jpg',
      'images/IMG_٢٠٢٣٠٥١٤_٢٠١٩٠٠.jpg',
    ],
    badge: 'sale',
    rating: 4.8,
    reviewCount: 35,
    inStock: true,
    stock: 7,
    featured: true,
    isNew: false,
    details: {
      material: { en: '80% Cotton, 20% Polyester Fleece', ar: '80% قطن، 20% بوليستر فليس' },
      care:     { en: 'Machine wash cold, do not bleach', ar: 'يُغسل في الغسالة بالماء البارد، لا تستخدم مبيض' },
      fit:      { en: 'Relaxed fit', ar: 'قصة مريحة واسعة' },
      weight:   { en: '~450g', ar: '~450 جرام' },
    },
  },
  {
    id: 'nm-003',
    name: { en: 'Track Jacket', ar: 'جاكيت تراك' },
    desc: {
      en: 'Water-resistant shell — built for the track, sharp enough for the street.',
      ar: 'قماش مقاوم للماء — مصمم للمضمار وأنيق بما يكفي للشارع.',
    },
    price: 200,
    originalPrice: null,
    category: 'outerwear',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Blue',  nameAr: 'أزرق', hex: '#2563EB' },
      { name: 'Black', nameAr: 'أسود', hex: '#1E293B' },
    ],
    image: 'images/IMG_٢٠٢٣٠٤١٠_١٦٣٤٢٨(1).jpg',
    images: [
      'images/IMG_٢٠٢٣٠٤١٠_١٦٣٤٢٨(1).jpg',
      'images/IMG_٢٠٢٣٠٥١٤_٢٠١٩٠٠.jpg',
      'images/IMG_٢٠٢٢١٢٢٢_١٥٢٥٤٨.jpg',
    ],
    badge: 'limited',
    rating: 4.7,
    reviewCount: 22,
    inStock: true,
    stock: 3,
    featured: true,
    isNew: false,
    details: {
      material: { en: '100% Nylon shell, mesh lining', ar: '100% نايلون خارجي، بطانة شبكية' },
      care:     { en: 'Wipe clean or hand wash', ar: 'يُمسح أو يُغسل باليد' },
      fit:      { en: 'Athletic fit', ar: 'قصة رياضية' },
      weight:   { en: '~350g', ar: '~350 جرام' },
    },
  },
  {
    id: 'nm-004',
    name: { en: 'Training Pants', ar: 'بنطلون تدريب' },
    desc: {
      en: 'Move freely — stretch-fit waistband for maximum comfort.',
      ar: 'تحرك بحرية — خصر مرن لأقصى قدر من الراحة.',
    },
    price: 150,
    originalPrice: null,
    category: 'bottoms',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Red',   nameAr: 'أحمر', hex: '#DC2626' },
      { name: 'Blue',  nameAr: 'أزرق', hex: '#2563EB' },
      { name: 'Black', nameAr: 'أسود', hex: '#1E293B' },
    ],
    image: 'images/IMG_٢٠٢٣٠٥١٤_٢٠١٩٠٠.jpg',
    images: [
      'images/IMG_٢٠٢٣٠٥١٤_٢٠١٩٠٠.jpg',
      'images/IMG_٢٠٢٢١٢٢٢_١٥٢٥٤٨.jpg',
      'images/IMG_٢٠٢٢١٢٢٦_١٩٢٦١٣.jpg',
    ],
    badge: null,
    rating: 4.6,
    reviewCount: 17,
    inStock: true,
    stock: 20,
    featured: false,
    isNew: false,
    details: {
      material: { en: '90% Polyester, 10% Elastane', ar: '90% بوليستر، 10% إيلاستين' },
      care:     { en: 'Machine wash cold', ar: 'يُغسل في الغسالة بالماء البارد' },
      fit:      { en: 'Slim fit', ar: 'قصة ضيقة' },
      weight:   { en: '~280g', ar: '~280 جرام' },
    },
  },
  {
    id: 'nm-005',
    name: { en: 'Sport Cap', ar: 'كاب رياضي' },
    desc: {
      en: 'Adjustable fit — block the sun, rep the brand.',
      ar: 'مقاس قابل للتعديل — احمي نفسك من الشمس واعرض البراند.',
    },
    price: 80,
    originalPrice: 100,
    category: 'accessories',
    sizes: ['One Size'],
    colors: [
      { name: 'Red',   nameAr: 'أحمر', hex: '#DC2626' },
      { name: 'Blue',  nameAr: 'أزرق', hex: '#2563EB' },
      { name: 'Black', nameAr: 'أسود', hex: '#1E293B' },
    ],
    image: 'images/Screenshot_٢٠٢٣-٠٥-٢١-٠٣-٠١-٢٤-٢٦٦_com.facebook.katana-edit.jpg',
    images: [
      'images/Screenshot_٢٠٢٣-٠٥-٢١-٠٣-٠١-٢٤-٢٦٦_com.facebook.katana-edit.jpg',
      'images/IMG_٢٠٢٢١٢٢٢_١٥٢٥٤٨.jpg',
      'images/IMG_٢٠٢٣٠٤١٠_١٦٣٤٢٨(1).jpg',
    ],
    badge: 'sale',
    rating: 4.5,
    reviewCount: 29,
    inStock: true,
    stock: 5,
    featured: false,
    isNew: false,
    details: {
      material: { en: '100% Cotton twill', ar: '100% قطن تويل' },
      care:     { en: 'Spot clean only', ar: 'التنظيف بالمسح فقط' },
      fit:      { en: 'Adjustable strap — fits 55-60cm', ar: 'حزام قابل للتعديل — يناسب 55-60 سم' },
      weight:   { en: '~85g', ar: '~85 جرام' },
    },
  },
  {
    id: 'nm-006',
    name: { en: 'Athletic Shorts', ar: 'شورت رياضي' },
    desc: {
      en: 'Lightweight, quick-dry fabric — ideal for intense training sessions.',
      ar: 'قماش خفيف وسريع الجفاف — مثالي لجلسات التدريب المكثفة.',
    },
    price: 90,
    originalPrice: null,
    category: 'bottoms',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Red',   nameAr: 'أحمر', hex: '#DC2626' },
      { name: 'Blue',  nameAr: 'أزرق', hex: '#2563EB' },
      { name: 'Black', nameAr: 'أسود', hex: '#1E293B' },
    ],
    image: 'images/IMG_٢٠٢٣٠٥١٤_٢٠١٩٠٠.jpg',
    images: [
      'images/IMG_٢٠٢٣٠٥١٤_٢٠١٩٠٠.jpg',
      'images/IMG_٢٠٢٢١٢٢٦_١٩٢٦١٣.jpg',
      'images/IMG_٢٠٢٣٠٤١٠_١٦٣٤٢٨(1).jpg',
    ],
    badge: 'new',
    rating: 4.6,
    reviewCount: 12,
    inStock: true,
    stock: 18,
    featured: false,
    isNew: true,
    details: {
      material: { en: '100% Polyester — quick-dry', ar: '100% بوليستر — سريع الجفاف' },
      care:     { en: 'Machine wash cold', ar: 'يُغسل في الغسالة بالماء البارد' },
      fit:      { en: 'Above-knee fit', ar: 'قصة فوق الركبة' },
      weight:   { en: '~150g', ar: '~150 جرام' },
    },
  },
  {
    id: 'nm-007',
    name: { en: 'Track Pants', ar: 'بنطلون تراك' },
    desc: {
      en: 'Side-stripe detail — classic athletic cut built to perform.',
      ar: 'تفصيلة شريط جانبي — قصة رياضية كلاسيكية مصممة للأداء.',
    },
    price: 160,
    originalPrice: null,
    category: 'bottoms',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Blue',  nameAr: 'أزرق', hex: '#2563EB' },
      { name: 'Black', nameAr: 'أسود', hex: '#1E293B' },
    ],
    image: 'images/IMG_٢٠٢٣٠٥١٤_٢٠١٩٠٠.jpg',
    images: [
      'images/IMG_٢٠٢٣٠٥١٤_٢٠١٩٠٠.jpg',
      'images/IMG_٢٠٢٣٠٤١٠_١٦٣٤٢٨(1).jpg',
      'images/IMG_٢٠٢٢١٢٢٢_١٥٢٥٤٨.jpg',
    ],
    badge: 'bestseller',
    rating: 4.8,
    reviewCount: 41,
    inStock: true,
    stock: 9,
    featured: false,
    isNew: false,
    details: {
      material: { en: '65% Polyester, 35% Cotton', ar: '65% بوليستر، 35% قطن' },
      care:     { en: 'Machine wash cold, iron low', ar: 'يُغسل بالماء البارد، يُكوي على حرارة منخفضة' },
      fit:      { en: 'Regular fit with elastic cuffs', ar: 'قصة عادية مع أساور مطاطية' },
      weight:   { en: '~320g', ar: '~320 جرام' },
    },
  },
  {
    id: 'nm-008',
    name: { en: 'Polo Shirt', ar: 'بولو شيرت' },
    desc: {
      en: 'Smart-casual pique fabric — from training to the cafe without changing.',
      ar: 'قماش بيكيه كاجوال أنيق — من التمرين للكافيه بدون تغيير.',
    },
    price: 110,
    originalPrice: null,
    category: 'tops',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Red',   nameAr: 'أحمر', hex: '#DC2626' },
      { name: 'Blue',  nameAr: 'أزرق', hex: '#2563EB' },
      { name: 'Black', nameAr: 'أسود', hex: '#1E293B' },
    ],
    image: 'images/IMG_٢٠٢٢١٢٢٢_١٥٢٥٤٨.jpg',
    images: [
      'images/IMG_٢٠٢٢١٢٢٢_١٥٢٥٤٨.jpg',
      'images/IMG_٢٠٢٢١٢٢٦_١٩٢٦١٣.jpg',
      'images/IMG_٢٠٢٣٠٥١٤_٢٠١٩٠٠.jpg',
    ],
    badge: 'new',
    rating: 4.5,
    reviewCount: 8,
    inStock: true,
    stock: 25,
    featured: false,
    isNew: true,
    details: {
      material: { en: '100% Cotton pique — 220 GSM', ar: '100% قطن بيكيه — 220 جرام/م²' },
      care:     { en: 'Machine wash cold, hang dry', ar: 'يُغسل بالماء البارد، يُنشّق بالهواء' },
      fit:      { en: 'Classic fit', ar: 'قصة كلاسيكية' },
      weight:   { en: '~230g', ar: '~230 جرام' },
    },
  },
  // ─── NEW PRODUCTS v4 — Fresh drops for New Arrivals section ───
  {
    id: 'nm-009',
    name: { en: 'Compression Base Layer', ar: 'طبقة ضغط داخلية' },
    desc: {
      en: 'Second-skin compression — supports muscles and boosts circulation during workouts.',
      ar: 'ضغط كالطبقة الثانية — يدعم العضلات ويحسن الدورة الدموية أثناء التمرين.',
    },
    price: 95,
    originalPrice: null,
    category: 'tops',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Black', nameAr: 'أسود', hex: '#1E293B' },
      { name: 'Blue',  nameAr: 'أزرق', hex: '#2563EB' },
    ],
    image: 'images/IMG_٢٠٢٢١٢٢٢_١٥٢٥٤٨.jpg',
    images: [
      'images/IMG_٢٠٢٢١٢٢٢_١٥٢٥٤٨.jpg',
      'images/IMG_٢٠٢٢١٢٢٦_١٩٢٦١٣.jpg',
    ],
    badge: 'new',
    rating: 4.7,
    reviewCount: 6,
    inStock: true,
    stock: 30,
    featured: false,
    isNew: true,
    details: {
      material: { en: '85% Nylon, 15% Spandex', ar: '85% نايلون، 15% سباندكس' },
      care:     { en: 'Machine wash cold, do not tumble dry', ar: 'يُغسل بالماء البارد، لا تجفف في النشافة' },
      fit:      { en: 'Compression / tight fit', ar: 'قصة ضيقة ضاغطة' },
      weight:   { en: '~160g', ar: '~160 جرام' },
    },
  },
  {
    id: 'nm-010',
    name: { en: 'Running Windbreaker', ar: 'جاكيت رياضي ضد الرياح' },
    desc: {
      en: 'Ultra-light windbreaker — packs into its own pocket for easy carrying.',
      ar: 'جاكيت خفيف جداً ضد الرياح — يُطوى في جيبه الخاص لسهولة الحمل.',
    },
    price: 185,
    originalPrice: 220,
    category: 'outerwear',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Red',   nameAr: 'أحمر', hex: '#DC2626' },
      { name: 'Black', nameAr: 'أسود', hex: '#1E293B' },
    ],
    image: 'images/IMG_٢٠٢٣٠٤١٠_١٦٣٤٢٨(1).jpg',
    images: [
      'images/IMG_٢٠٢٣٠٤١٠_١٦٣٤٢٨(1).jpg',
      'images/IMG_٢٠٢٣٠٥١٤_٢٠١٩٠٠.jpg',
    ],
    badge: 'sale',
    rating: 4.9,
    reviewCount: 15,
    inStock: true,
    stock: 8,
    featured: false,
    isNew: true,
    details: {
      material: { en: '100% Ripstop Nylon', ar: '100% نايلون ريبستوب' },
      care:     { en: 'Wipe clean or hand wash', ar: 'التنظيف بالمسح أو الغسل باليد' },
      fit:      { en: 'Regular fit — packs to 15x10cm', ar: 'قصة عادية — يُطوى لـ 15×10 سم' },
      weight:   { en: '~120g', ar: '~120 جرام' },
    },
  },
  {
    id: 'nm-011',
    name: { en: 'Gym Tank Top', ar: 'تانك توب رياضي' },
    desc: {
      en: 'Maximum airflow — racerback cut with dropped armholes for unrestricted movement.',
      ar: 'تهوية قصوى — قصة رايسر باك مع فتحات واسعة لحركة غير مقيدة.',
    },
    price: 65,
    originalPrice: null,
    category: 'tops',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Red',   nameAr: 'أحمر', hex: '#DC2626' },
      { name: 'Blue',  nameAr: 'أزرق', hex: '#2563EB' },
      { name: 'Black', nameAr: 'أسود', hex: '#1E293B' },
    ],
    image: 'images/IMG_٢٠٢٢١٢٢٦_١٩٢٦١٣.jpg',
    images: [
      'images/IMG_٢٠٢٢١٢٢٦_١٩٢٦١٣.jpg',
      'images/IMG_٢٠٢٢١٢٢٢_١٥٢٥٤٨.jpg',
    ],
    badge: 'new',
    rating: 4.6,
    reviewCount: 9,
    inStock: true,
    stock: 22,
    featured: false,
    isNew: true,
    details: {
      material: { en: '100% Polyester mesh', ar: '100% بوليستر شبكي' },
      care:     { en: 'Machine wash cold', ar: 'يُغسل في الغسالة بالماء البارد' },
      fit:      { en: 'Relaxed fit with racerback', ar: 'قصة مريحة مع رايسر باك' },
      weight:   { en: '~110g', ar: '~110 جرام' },
    },
  },
  {
    id: 'nm-012',
    name: { en: 'Sports Socks (3-Pack)', ar: 'شرابات رياضية (3 أزواج)' },
    desc: {
      en: 'Cushioned heel and toe — moisture-wicking with arch support.',
      ar: 'كعب ومقدمة مبطنة — تسحب الرطوبة مع دعم للقوس.',
    },
    price: 70,
    originalPrice: 90,
    category: 'accessories',
    sizes: ['One Size'],
    colors: [
      { name: 'Black', nameAr: 'أسود', hex: '#1E293B' },
      { name: 'Blue',  nameAr: 'أزرق', hex: '#2563EB' },
    ],
    image: 'images/Screenshot_٢٠٢٣-٠٥-٢١-٠٣-٠١-٢٤-٢٦٦_com.facebook.katana-edit.jpg',
    images: [
      'images/Screenshot_٢٠٢٣-٠٥-٢١-٠٣-٠١-٢٤-٢٦٦_com.facebook.katana-edit.jpg',
      'images/IMG_٢٠٢٢١٢٢٢_١٥٢٥٤٨.jpg',
    ],
    badge: 'sale',
    rating: 4.4,
    reviewCount: 31,
    inStock: true,
    stock: 40,
    featured: false,
    isNew: true,
    details: {
      material: { en: '80% Cotton, 15% Polyester, 5% Spandex', ar: '80% قطن، 15% بوليستر، 5% سباندكس' },
      care:     { en: 'Machine wash cold', ar: 'يُغسل في الغسالة بالماء البارد' },
      fit:      { en: 'Fits EU 39-45', ar: 'يناسب مقاس 39-45 أوروبي' },
      weight:   { en: '~90g per pack', ar: '~90 جرام للعبوة' },
    },
  },
];

// ============================================================
//  TESTIMONIALS DATA
//  Add/edit reviews here without touching the HTML.
// ============================================================
const TESTIMONIALS = [
  {
    name: 'Ahmed M.',
    city: { en: 'Cairo', ar: 'القاهرة' },
    stars: 5,
    text: {
      en: "The hoodie quality is amazing. I've washed it 10 times and it still looks brand new. Fast delivery, only 2 days!",
      ar: 'جودة الهودي رهيبة. غسلتها 10 مرات وبالظبط زي الجديد. توصيل سريع، يومين بس!',
    },
    verified: true,
  },
  {
    name: 'Sara K.',
    city: { en: 'Alexandria', ar: 'الإسكندرية' },
    stars: 5,
    text: {
      en: 'Ordered the jacket and pants together. Great fit, great price. Cash on delivery made it super easy. Will order again.',
      ar: 'طلبت الجاكيت والبنطلون مع بعض. مقاس تمام، سعر ممتاز. الدفع عند الاستلام سهّل الأمر كتير. هطلب تاني.',
    },
    verified: true,
  },
  {
    name: 'Mohamed R.',
    city: { en: 'Giza', ar: 'الجيزة' },
    stars: 5,
    text: {
      en: 'I got the wrong size by mistake, they exchanged it with no problem. Excellent customer service. 10/10 recommend.',
      ar: 'طلبت مقاس غلط بالغلط، استبدلوه من غير أي مشاكل. خدمة عملاء ممتازة. 10/10 أنصح بيهم.',
    },
    verified: true,
  },
  {
    name: 'Nour H.',
    city: { en: 'Mansoura', ar: 'المنصورة' },
    stars: 4,
    text: {
      en: 'Very good quality for the price. The T-shirt material feels premium, not the usual thin fabric.',
      ar: 'جودة ممتازة للسعر. قماش التيشيرت بريميوم، مش الخامة الرفيعة العادية.',
    },
    verified: true,
  },
  {
    name: 'Karim T.',
    city: { en: 'Ismailia', ar: 'الإسماعيلية' },
    stars: 5,
    text: {
      en: "Best sportswear shop I've found online in Egypt. Fair prices, real quality. The cap is my favorite piece.",
      ar: 'أحسن محل ملابس رياضية اونلاين في مصر. أسعار معقولة وجودة حقيقية. الكاب هو المفضل عندي.',
    },
    verified: true,
  },
];

// ─── Size Guide Data (cm) ──────────────────────────────────
const SIZE_GUIDE = {
  en: {
    title: 'Size Guide',
    subtitle: 'All measurements are in centimeters (cm).',
    headers: ['Size', 'Chest', 'Waist', 'Hips', 'Length'],
    rows: [
      { size: 'S',  chest: '96',  waist: '82',  hips: '96',  length: '68' },
      { size: 'M',  chest: '104', waist: '90',  hips: '104', length: '70' },
      { size: 'L',  chest: '112', waist: '98',  hips: '112', length: '72' },
      { size: 'XL', chest: '120', waist: '106', hips: '120', length: '74' },
    ],
    note: 'If you are between sizes, we recommend ordering the larger size for a comfortable fit.',
  },
  ar: {
    title: 'دليل المقاسات',
    subtitle: 'جميع القياسات بالسنتيمتر (سم).',
    headers: ['المقاس', 'الصدر', 'الخصر', 'الورك', 'الطول'],
    rows: [
      { size: 'S',  chest: '96',  waist: '82',  hips: '96',  length: '68' },
      { size: 'M',  chest: '104', waist: '90',  hips: '104', length: '70' },
      { size: 'L',  chest: '112', waist: '98',  hips: '112', length: '72' },
      { size: 'XL', chest: '120', waist: '106', hips: '120', length: '74' },
    ],
    note: 'إذا كنت بين مقاسين، ننصح بطلب المقاس الأكبر لراحة أفضل.',
  },
};
